In [1]:
import numpy as np
import math as mh
import matplotlib.pyplot as plt
from sympy import diff

In [2]:
g0 = 5/3
ro0 = 1.694*10**(-4)
p0 = 1.013*10**(6)
u0 = 0
g3 = 7/5
c3 = 3.6537*10**(4)
u3 = 1.229*10**(4)
p3 = 1.6768*10**(6)
e = 10**(-5)

Найдем величины, которые есть в уравнении: 

In [3]:
n = (2*g3)/(g3-1);
print("n =", n);

a0 = (g0+1)/(g0-1);
print("a0 =", a0);

ro3 = (g3*p3)/(c3**2);
print("ro3 =", ro3)

mu = (u3-u0)*(((g0-1)*ro0)/(2*p0)**(1/2));
print("mu = ", mu);

nu = (2/(g3-1))*(((g3*(g0-1)*p3*ro0)/(2*p0*ro3))**(1/2));
print("nu =", nu);

x = p3/p0;
print("x =", x);

n = 7.000000000000001
a0 = 4.0
ro3 = 0.0017585046886418162
mu =  0.0009751115695652081
nu = 1.363936785446444
x = 1.6552813425468906


Посчитаем коэффициенты уравнения: $X^2 Z^{2n} - \alpha_0 \nu^2 XZ^{n+2} + 2\alpha_0 \nu(\mu + \nu)X Z^{n+1} - [2 + (\mu + \nu)^2 \alpha_0]X Z^{n} - \nu^2 Z^2 + 2\nu(\mu + \nu)Z - (\mu + \nu)^2 + 1 = 0$

In [4]:
b1 = (x**2);
print("b1 =", b1);

b2 = (-a0)*(nu**2)*x;
print("b2 =", b2);

b3 = 2*a0*nu*(mu+nu)*x;
print("b3 =", b3);

b4 = -(2+((mu+nu)**2)*a0)*x;
print("b4 =", b4);

b5 = (-1)*(nu**2);
print("b5 =", b5);

b6 = (2*nu*(mu+nu));
print("b6 =", b6);

b7 = (-1)*((mu+nu)**2)+1;
print("b7 =", b7);


b1 = 2.739956322983837
b2 = -12.317435484741813
b3 = 24.652483037691926
b4 = -15.645616533691777
b5 = -1.8603235546939787
b6 = 3.7233070904672467
b7 = -0.8629844866158409


Найдем кольцо, в котором расположены корни:

$\frac{|b_{n}|}{|b_{n}|+B} \leqslant |z| \leqslant 1+\frac{A}{|b_{0}|}$ (обозначения из лабника)

In [5]:
A = max([abs(b2), abs(b3), abs(b4), abs(b5), abs(b6), abs(b7)])
B = max([abs(b1), abs(b2), abs(b3), abs(b4), abs(b5), abs(b6)])
left_border = (abs(b7))/((abs(b7)+B))
right_border = (1 + (A/abs(b1)));   
print(left_border, "<= |z| <=", right_border)

0.03382201348235941 <= |z| <= 9.99740000630563


Попробуем локализовать корни уравнения с помощью теоремы Декарта:
$f(z) = b_{1}*z^{14} + b_{2}*z^{9} + b_{3}*z^{8} + b_{4}*z^{7} + b_{5}*z^{2} + b_{6}*z + b_{7} = 0$

Для f(z) число перемен знака равно 5 => число положительных действительных корней равно 5, или 3, или 1

Для f(-z) число перемен знака равно 1 => число отрицательных действительных корней равно 1


Напишем алгоритм для подсчета n-ой производной:

degrees = [1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1]
koeffs = [b7, b6, b5, 0, 0, 0, 0, b4, b3, b2, 0, 0, 0, 0, b1]
def n_der(n):
    k = 14
    for i in range(n):
        for j in range(k):
            koeffs[j] = koeffs[j+1]*(j+1)
            degrees[j] = degrees[j+1]
        koeffs[k] = 0
        degrees[k] = 0
        k = k - 1

Локализуем корни по теореме Бюдана-Фурье: для этого разобьем область нахождения корней на 10000 отрезков будем фиксировать разность количества смен знака между промежутками. 

In [ ]:
n_der(1)
koeffs1 = [koeffs]
print(*koeffs1, sep=', ')

n_der(1)
koeffs2 = [koeffs]
print(*koeffs2, sep=', ')

n_der(1)
koeffs3 = [koeffs]
print(*koeffs3, sep=', ')

n_der(1)
koeffs4 = [koeffs]
print(*koeffs4, sep=', ')

n_der(1)
koeffs5 = [koeffs]
print(*koeffs5, sep=', ')

print("...............................")
n_der(1)
koeffs6 = [koeffs]
n_der(1)
koeffs7 = [koeffs]
n_der(1)
koeffs8 = [koeffs]
n_der(1)
koeffs9 = [koeffs]
n_der(1)
koeffs10 = [koeffs]
n_der(1)
koeffs11 = [koeffs]
n_der(1)
koeffs12 = [koeffs]
n_der(1)
koeffs13 = [koeffs]
n_der(1)
koeffs14 = [koeffs]
print(*koeffs14, sep=', ')

def sign(a,b, sign):
    if ((a > 0 and b < 0) or (a < 0 and b > 0) or (a!=b!=0)):
        sign += 1;

segments = []        
delta = 0.02
p = -10
numbers=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
while p<=10:
        s0 = [] 
        s1 = []
        s2 = []
        s3 = []
        s4 = []
        s5 = []
        s6 = []
        s7 = []
        s8 = []
        s9 = []
        s10 = []
        s11 = []
        s12 = []
        s13 = []
        s14 = []
        sgn = 0
        for i,j in zip(numbers, koeffs):
            x = j*((p)**(i))
            s0.append(x)
        summ0 = sum(s0)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ0, summ1, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ1, summ2, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ2, summ3, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ3, summ4, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ4, summ5, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ5, summ6, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ6, summ7, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ7, summ8, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ8, summ9, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ9, summ10, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ10, summ11, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ11, summ12, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ12, summ13, sgn)
        for i,j in zip(numbers, koeffs1):
            x = j*((p)**(i))
            s1.append(x)
        summ1 = sum(s1)
        sign(summ13, summ14, sgn)
        sgn1 = sgn
        sgn = 0
        
        summ0 = 0 
        summ1 = 0
        summ2 = 0
        summ3 = 0
        summ4 = 0
        summ5 = 0
        summ6 = 0
        summ7 = 0
        summ8 = 0
        summ9 = 0
        summ10 = 0
        summ11 = 0
        summ12 = 0
        summ13 = 0
        summ14 = 0
        
        p += delta
        for i,j in zip(numbers, koeffs):
            summ0 = summ0 + j*((p)**(i))
        for i,j in zip(numbers, koeffs1):
            summ1 = summ1 + j*((p)**(i))
        sign(summ0, summ1, sgn)
        for i,j in zip(numbers, koeffs2):
            summ2 = summ2 + j*((p)**(i))
        sign(summ1, summ2, sgn)
        for i,j in zip(numbers, koeffs3):
            summ3 = summ3 + j*((p)**(i))
        sign(summ2, summ3, sgn)
        for i,j in zip(numbers, koeffs4):
            summ4 = summ4 + j*((p)**(i))
        sign(summ3, summ4, sgn)
        for i,j in zip(numbers, koeffs5):
            summ5 = summ5 + j*((p)**(i))
        sign(summ4, summ5, sgn)
        for i,j in zip(numbers, koeffs6):
            summ6 = summ6 + j*((p)**(i))
        sign(summ5, summ6, sgn)
        for i,j in zip(numbers, koeffs7):
            summ7 = summ7 + j*((p)**(i))
        sign(summ6, summ7, sgn)
        for i,j in zip(numbers, koeff8):
            summ8 = summ8 + j*((p)**(i))
        sign(summ7, summ8, sgn)
        for i,j in zip(numbers, koeffs9):
            summ9 = summ9 + j*((p)**(i))
        sign(summ8, summ9, sgn)
        for i,j in zip(numbers, koeffs10):
            summ10 = summ10 + j*((p)**(i))
        sign(summ9, summ10, sgn)
        for i,j in zip(numbers, koeffs11):
            summ11 = summ11 + j*((p)**(i))
        sign(summ10, summ11, sgn)
        for i,j in zip(numbers, koeffs12):
            summ12 = summ12 + j*((p)**(i))
        sign(summ11, summ12, sgn)
        for i,j in zip(numbers, koeffs13):
            summ13 = summ13 + j*((p)**(i))
        sign(summ12, summ13, sgn)
        for i,j in zip(numbers, koeffs14):
            summ14 = summ14 + j*((p)**(i))
        sign(summ13, summ14, sgn)
        sgn2 = sgn 
        if (sgn1 != sgn2):
            segment.append(p)
            segment.append(p-delta)
print(*segments, sep=", ")        
        


По Бюдану-Фурье не получаеца, будем делить отрезки;(

In [6]:
def function(z):
    global b
    return b1*z**(14) + b2*z**(9) + b3*z**(8) + b4*z**(7) + b5*z**2 + b6*z + b7
def sign(f):
    if f>0:
        return 1
    else:
        return 0
N = 1000 #начинаем делить с 1000 отрезков
segments = np.linspace(left_border, right_border, N)
while (segments[1]-segments[0]>e):
    N *= 10
    segments = np.linspace(left_border, right_border, N)
print("N = ", N, "- кол-во отрезков")

len_s = (right_border - left_border)/N
print("Delta = ", len_s, "длина одного отрезка")

N =  1000000 - кол-во отрезков
Delta =  9.963577992823272e-06 длина одного отрезка


Определим индексы отрезков, сами отрезки и значения корней на них:

In [7]:
index_pos = []
for i in range(n-1):
    if sign(function(left_border + i*len_s)) != sign(function(left_border + (i+1)*len_s)):
        index_pos.append(i)
print(*index_pos, sep=", ") 

TypeError: 'float' object cannot be interpreted as an integer

In [49]:
index_neg = []
for i in range(n-1):
    if sign(function(-right_border + i*len_s)) != sign(function(-right_border + (i+1)*len_s)):
        index_neg.append(i)
print(*index_neg, sep=", ") 

929895


Сами отрезки и корни:

In [50]:
left = []
right = []
for i in (index_pos):
    left.append((left_border + i*len_s))
    right.append((left_border + (i+1)*len_s))

for i in (index_neg):
    left.append((-right_border + i*len_s))
    right.append((-right_border + (i+1)*len_s))
    
for i,j in zip(left, right):
    print(i,j)

0.2678963512677565 0.26790631484574934
0.8817723185615839 0.8817822821395767
0.9507103146939281 0.950720278271921
-0.732318648669235 -0.7323086850912421


In [51]:
z = []
for i in (index_pos):
    z.append(left_border + ((2*i + 1)*len_s)/2)
for i in (index_neg):
    z.append(-right_border + ((2*i + 1)*len_s)/2)
print(*z, sep=", ")

0.26790133305675295, 0.8817773003505803, 0.9507152964829245, -0.7323136668802377


In [52]:
solutions = np.array(z)
solutions = solutions.round(5)
solutions

array([ 0.2679 ,  0.88178,  0.95072, -0.73231])

Из условия $Z = \frac{P_{1}}{P_{3}}^{1/n}$

In [58]:
p1 = p3*(solutions**int(7))
p1

array([ 1.66069646e+02,  6.95029078e+05,  1.17719844e+06, -1.89385192e+05])

Очевидно, последний элемент массива не подходит, т.к. давление не может быть отрицательным. Определим скорость ударной волны:

In [60]:
c2 = c3*solutions
u1 = u3 + (2*(c3 - c2))/(g3 - 1)
u1[0:3]

array([146033.6885,  33887.0207,  21292.7168])

$D_0 = U_0 + \frac{P_1 - P_0}{\rho_0(U_1 - U_0)}$

In [63]:
d0 = u0 + (p1 - p0)/(ro0*(u1[0:3] - u0))
d0.round(3)

array([-40942.257, -55391.179,  45522.335])